In [9]:
year = int(input())
year = (year % 4 == 0) & ((year % 100 != 0) | (year % 400 == 0))
print(year)


True


In [12]:
import numpy as np 
np.random.seed(228)

In [ ]:
x = np.array([1,2,3,4])

In [16]:
a = np.ones(3)          # array from '1'
b = np.zeros(3)         # array from '0'
b

array([0., 0., 0.])

In [18]:
# array adding
c = a + b 
print(c)

[1. 1. 1.]


In [20]:
a = np.arange(1,100,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [37]:
type(a)
a.ndim          # number of dimensions
a.shape         # shape of array
np.mean(a)      # 
a.max()
a.min()
np.median(a)
r = np.random.random((5,5))
print(r)


[[0.8525484  0.46738664 0.51298253 0.90667453 0.75392503]
 [0.7673017  0.65124248 0.36187417 0.98591306 0.32099692]
 [0.40826557 0.42393802 0.93590116 0.12134319 0.33511246]
 [0.33535646 0.88760079 0.93175833 0.91599886 0.32327427]
 [0.93101166 0.43111956 0.4950566  0.60468477 0.76853971]]
